/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Ampli - A strong typed wrapper for your Analytics
 *
 * This file is generated by Amplitude.
 * To update run 'ampli pull cm-website'
 *
 * Required dependencies: @amplitude/analytics-browser@^1.3.0
 * Tracking Plan Version: 2
 * Build: 1.0.0
 * Runtime: browser:typescript-ampli-v2
 *
 * [View Tracking Plan](https://data.eu.amplitude.com/tmlmobilidade/default/events/main/latest)
 *
 * [Full Setup Instructions](https://data.eu.amplitude.com/tmlmobilidade/default/implementation/cm-website)
 */

import * as amplitude from '@amplitude/analytics-browser';

export type Environment = 'default';

export const ApiKey: Record<Environment, string> = {
  default: '66aabe34bf2c52425e3dd7ab51c683e1'
};

/**
 * Default Amplitude configuration options. Contains tracking plan information.
 */
export const DefaultConfiguration: BrowserOptions = {
  plan: {
    version: '2',
    branch: 'main',
    source: 'cm-website',
    versionId: 'c1eb6e9c-4fdb-4e52-a3e8-6bca97569cf4'
  },
  ...{
    ingestionMetadata: {
      sourceName: 'browser-typescript-ampli',
      sourceVersion: '2.0.0'
    }
  },
  serverZone: amplitude.Types.ServerZone.EU
};

export interface LoadOptionsBase { disabled?: boolean }

export type LoadOptionsWithEnvironment = LoadOptionsBase & { environment: Environment; client?: { configuration?: BrowserOptions; }; };
export type LoadOptionsWithApiKey = LoadOptionsBase & { client: { apiKey: string; configuration?: BrowserOptions; } };
export type LoadOptionsWithClientInstance = LoadOptionsBase & { client: { instance: BrowserClient; } };

export type LoadOptions = LoadOptionsWithEnvironment | LoadOptionsWithApiKey | LoadOptionsWithClientInstance;

export interface AddFavoriteLineProperties {
  /**
   * Holds a the ID of the entity "Line", which is usually a 4-digit numeric string.
   */
  line_id: string;
}

export interface AddFavoriteStopProperties {
  /**
   * Holds a the ID of the entity "Stop", which is always a 6-digit numeric string.
   *
   * | Rule | Value |
   * |---|---|
   * | Min Length | 6 |
   * | Max Length | 6 |
   */
  stop_id: string;
}

export interface ClickDebugToggleProperties {
  is_enabled: string;
}

export interface ClickLinkProperties {
  /**
   * This property indicates the location in the app (the pathname, the screen id) where the current event was generated at.
   */
  current_page: string;
  /**
   * This property indicates the href of the destination URL. This is used when the user is navigating out of the current screen by means of a link (either in-app or in a website).
   */
  destination_href: string;
}

export interface PingProperties {
  /**
   * The version of the application that generated the event.
   */
  app_version: string;
  /**
   * This property indicates the location in the app (the pathname, the screen id) where the current event was generated at.
   */
  current_page: string;
}

export interface RemoveFavoriteLineProperties {
  /**
   * Holds a the ID of the entity "Line", which is usually a 4-digit numeric string.
   */
  line_id: string;
}

export interface RemoveFavoriteStopProperties {
  /**
   * Holds a the ID of the entity "Stop", which is always a 6-digit numeric string.
   *
   * | Rule | Value |
   * |---|---|
   * | Min Length | 6 |
   * | Max Length | 6 |
   */
  stop_id: string;
}

export class AcceptAnalyticsConsent implements BaseEvent {
  event_type = 'Accept Analytics Consent';
}

export class AddFavoriteLine implements BaseEvent {
  event_type = 'Add Favorite Line';

  constructor(
    public event_properties: AddFavoriteLineProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class AddFavoriteStop implements BaseEvent {
  event_type = 'Add Favorite Stop';

  constructor(
    public event_properties: AddFavoriteStopProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class ClickDebugToggle implements BaseEvent {
  event_type = 'Click Debug Toggle';

  constructor(
    public event_properties: ClickDebugToggleProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class ClickLink implements BaseEvent {
  event_type = 'Click Link';

  constructor(
    public event_properties: ClickLinkProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class Ping implements BaseEvent {
  event_type = 'Ping';

  constructor(
    public event_properties: PingProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class RemoveFavoriteLine implements BaseEvent {
  event_type = 'Remove Favorite Line';

  constructor(
    public event_properties: RemoveFavoriteLineProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class RemoveFavoriteStop implements BaseEvent {
  event_type = 'Remove Favorite Stop';

  constructor(
    public event_properties: RemoveFavoriteStopProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export type PromiseResult<T> = { promise: Promise<T | void> };

const getVoidPromiseResult = () => ({ promise: Promise.resolve() });

// prettier-ignore
export class Ampli {
  private disabled: boolean = false;
  private amplitude?: BrowserClient;

  get client(): BrowserClient {
    this.isInitializedAndEnabled();
    return this.amplitude!;
  }

  get isLoaded(): boolean {
    return this.amplitude != null;
  }

  private isInitializedAndEnabled(): boolean {
    if (!this.amplitude) {
      console.error('ERROR: Ampli is not yet initialized. Have you called ampli.load() on app start?');
      return false;
    }
    return !this.disabled;
  }

  /**
   * Initialize the Ampli SDK. Call once when your application starts.
   *
   * @param options Configuration options to initialize the Ampli SDK with.
   */
  load(options: LoadOptions): PromiseResult<void> {
    this.disabled = options.disabled ?? false;

    if (this.amplitude) {
      console.warn('WARNING: Ampli is already intialized. Ampli.load() should be called once at application startup.');
      return getVoidPromiseResult();
    }

    let apiKey: string | null = null;
    if (options.client && 'apiKey' in options.client) {
      apiKey = options.client.apiKey;
    } else if ('environment' in options) {
      apiKey = ApiKey[options.environment];
    }

    if (options.client && 'instance' in options.client) {
      this.amplitude = options.client.instance;
    } else if (apiKey) {
      this.amplitude = amplitude.createInstance();
      const configuration = (options.client && 'configuration' in options.client) ? options.client.configuration : {};
      return this.amplitude.init(apiKey, undefined, { ...DefaultConfiguration, ...configuration });
    } else {
      console.error("ERROR: ampli.load() requires 'environment', 'client.apiKey', or 'client.instance'");
    }

    return getVoidPromiseResult();
  }

  /**
   * Identify a user and set user properties.
   *
   * @param userId The user's id.
   * @param options Optional event options.
   */
  identify(
    userId: string | undefined,
    options?: EventOptions,
  ): PromiseResult<Result> {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    if (userId) {
      options = {...options,  user_id: userId};
    }

    const amplitudeIdentify = new amplitude.Identify();
    return this.amplitude!.identify(
      amplitudeIdentify,
      options,
    );
  }

 /**
  * Flush the event.
  */
  flush() : PromiseResult<Result> {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    return this.amplitude!.flush();
  }

  /**
   * Track event
   *
   * @param event The event to track.
   * @param options Optional event options.
   */
  track(event: Event, options?: EventOptions): PromiseResult<Result> {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    return this.amplitude!.track(event, undefined, options);
  }

  /**
   * Accept Analytics Consent
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/tmlmobilidade/default/events/main/latest/Accept%20Analytics%20Consent)
   *
   * Event has no description in tracking plan.
   *
   * @param options Amplitude event options.
   */
  acceptAnalyticsConsent(
    options?: EventOptions,
  ) {
    return this.track(new AcceptAnalyticsConsent(), options);
  }

  /**
   * Add Favorite Line
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/tmlmobilidade/default/events/main/latest/Add%20Favorite%20Line)
   *
   * Event to track when a user adds a public transportation line to their list of favorites for quick access and personalized recommendations.
   *
   * @param properties The event's properties (e.g. line_id)
   * @param options Amplitude event options.
   */
  addFavoriteLine(
    properties: AddFavoriteLineProperties,
    options?: EventOptions,
  ) {
    return this.track(new AddFavoriteLine(properties), options);
  }

  /**
   * Add Favorite Stop
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/tmlmobilidade/default/events/main/latest/Add%20Favorite%20Stop)
   *
   * Event to track when a user adds a stop to their favorites list.
   *
   * @param properties The event's properties (e.g. stop_id)
   * @param options Amplitude event options.
   */
  addFavoriteStop(
    properties: AddFavoriteStopProperties,
    options?: EventOptions,
  ) {
    return this.track(new AddFavoriteStop(properties), options);
  }

  /**
   * Click Debug Toggle
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/tmlmobilidade/default/events/main/latest/Click%20Debug%20Toggle)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. is_enabled)
   * @param options Amplitude event options.
   */
  clickDebugToggle(
    properties: ClickDebugToggleProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickDebugToggle(properties), options);
  }

  /**
   * Click Link
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/tmlmobilidade/default/events/main/latest/Click%20Link)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. current_page)
   * @param options Amplitude event options.
   */
  clickLink(
    properties: ClickLinkProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickLink(properties), options);
  }

  /**
   * Ping
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/tmlmobilidade/default/events/main/latest/Ping)
   *
   * Event to track when a user visits CMetropolitana website.
   *
   * @param properties The event's properties (e.g. app_version)
   * @param options Amplitude event options.
   */
  ping(
    properties: PingProperties,
    options?: EventOptions,
  ) {
    return this.track(new Ping(properties), options);
  }

  /**
   * Remove Favorite Line
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/tmlmobilidade/default/events/main/latest/Remove%20Favorite%20Line)
   *
   * Event to track when a user removes a specific public transportation line from their list of favorites.
   *
   * @param properties The event's properties (e.g. line_id)
   * @param options Amplitude event options.
   */
  removeFavoriteLine(
    properties: RemoveFavoriteLineProperties,
    options?: EventOptions,
  ) {
    return this.track(new RemoveFavoriteLine(properties), options);
  }

  /**
   * Remove Favorite Stop
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/tmlmobilidade/default/events/main/latest/Remove%20Favorite%20Stop)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. stop_id)
   * @param options Amplitude event options.
   */
  removeFavoriteStop(
    properties: RemoveFavoriteStopProperties,
    options?: EventOptions,
  ) {
    return this.track(new RemoveFavoriteStop(properties), options);
  }
}

export const ampli = new Ampli();

// BASE TYPES
type BrowserOptions = amplitude.Types.BrowserOptions;

export type BrowserClient = amplitude.Types.BrowserClient;
export type BaseEvent = amplitude.Types.BaseEvent;
export type IdentifyEvent = amplitude.Types.IdentifyEvent;
export type GroupEvent = amplitude.Types.GroupIdentifyEvent;
export type Event = amplitude.Types.Event;
export type EventOptions = amplitude.Types.EventOptions;
export type Result = amplitude.Types.Result;
