# # #

name: 'Website | Build & Push'

# # #

on:
  workflow_dispatch:
  push:
    branches:
      - production
      - staging
      - sandbox

# # #

jobs:

  # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # #

  nginx:
    name: nginx
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@master
        with:
          push: true
          file: ./apps/nginx/Dockerfile
          tags: ghcr.io/carrismetropolitana/website-nginx:${{ github.ref_name }}
          build-args: |
            ENVIRONMENT=${{ github.ref_name }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  backoffice:
    name: backoffice (NextJS)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@master
        with:
          push: true
          file: ./apps/backoffice/Dockerfile
          tags: ghcr.io/carrismetropolitana/website-backoffice:${{ github.ref_name }}
          build-args: |
            ENVIRONMENT=${{ github.ref_name }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  frontend:
    name: frontend (NextJS)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@master
        with:
          push: true
          file: ./apps/frontend/Dockerfile
          tags: ghcr.io/carrismetropolitana/website-frontend:${{ github.ref_name }}
          build-args: |
            ENVIRONMENT=${{ github.ref_name }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  schools:
    name: schools (NextJS)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@master
        with:
          push: true
          file: ./apps/schools/Dockerfile
          tags: ghcr.io/carrismetropolitana/website-schools:${{ github.ref_name }}
          build-args: |
            ENVIRONMENT=${{ github.ref_name }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  pips:
    name: pips (NextJS)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@master
        with:
          push: true
          file: ./apps/pips/Dockerfile
          tags: ghcr.io/carrismetropolitana/website-pips:${{ github.ref_name }}
          build-args: |
            ENVIRONMENT=${{ github.ref_name }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  backupd:
    name: backupd (MongoDB Backup)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@master
        with:
          push: true
          file: ./apps/backupd/Dockerfile
          tags: ghcr.io/carrismetropolitana/website-backupd:${{ github.ref_name }}
          build-args: |
            ENVIRONMENT=${{ github.ref_name }}
